version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - .client/node_modules
      - ./client:/app/
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - .server/node_modules
      - ./server:/app/