version: "3.9"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./app:/app/
  users:
    build:
      context: ./users
      dockerfile: Dockerfile.dev
    ports:
      - 6000:6000
    volumes:
      - /users/node_modules
      - ./users:/app/
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /client/node_modules
      - ./client:/app/
