version: "3.9"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./app:/app/
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /client/node_modules
      - ./client:/app/
