name: Deploy to Heroku
on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push Release to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          docker_directory: ./client
          dockerfile_name: ./client/Dockerfile
          docker_options: "--no-cache"
          process_type: web
