name: Testing React Application
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build React Image for running tests
        run: docker build --tag ${{secrets.DOCKER_HUB_USERNAME}}/chat-app-client -f ./client/Dockerfile.dev ./client

      - name: Run React Tests
        run: docker run -e CI=true ${{secrets.DOCKER_HUB_USERNAME}}/chat-app-client npm test
    
